# Generated by Django 5.2.12 on 2026-04-17 11:44

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GymNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, choices=[('🎉', '🎉 Party / Offer'), ('💪', '💪 Training'), ('🏖️', '🏖️ Summer / Season'), ('⚡', '⚡ Alert / Closure'), ('🏷️', '🏷️ Deal / Discount'), ('📢', '📢 Announcement'), ('', 'No icon')], default='📢', max_length=5)),
                ('message', models.CharField(help_text='Short notification text (max 200 chars)', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower number = shows first')),
            ],
            options={
                'verbose_name': 'Gym Notification',
                'verbose_name_plural': 'Gym Notifications',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('duration_days', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(db_index=True, editable=False, max_length=4, unique=True)),
                ('fullname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('phone', models.CharField(db_index=True, max_length=10)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=30, null=True)),
                ('paymentStatus', models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pendingAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paymentMethod', models.CharField(blank=True, choices=[('C', 'CASH'), ('U', 'UPI'), ('B', 'UPI + CASH')], max_length=1, null=True)),
                ('doj', models.DateField(auto_now_add=True)),
                ('DueDate', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('face_enrolled', models.BooleanField(default=False)),
                ('face_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('face_embeddings', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('selectPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.membershipplan')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Attendance.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('timestamp', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
